import Ember from 'ember';

export default Ember.Mixin.create({
    allStates: [
        { value: "AL", text: "Alabama"},
        { value: "AK", text: "Alaska"},
        { value: "AS", text: "American Samoa"},
        { value: "AZ", text: "Arizona"},
        { value: "AR", text: "Arkansas"},
        { value: "CA", text: "California"},
        { value: "CO", text: "Colorado"},
        { value: "CT", text: "Connecticut"},
        { value: "DE", text: "Delaware"},
        { value: "DC", text: "District Of Columbia"},
        { value: "FM", text: "Federated States Of Micronesia"},
        { value: "FL", text: "Florida"},
        { value: "GA", text: "Georgia"},
        { value: "GU", text: "Guam"},
        { value: "HI", text: "Hawaii"},
        { value: "ID", text: "Idaho"},
        { value: "IL", text: "Illinois"},
        { value: "IN", text: "Indiana"},
        { value: "IA", text: "Iowa"},
        { value: "KS", text: "Kansas"},
        { value: "KY", text: "Kentucky"},
        { value: "LA", text: "Louisiana"},
        { value: "ME", text: "Maine"},
        { value: "MH", text: "Marshall Islands"},
        { value: "MD", text: "Maryland"},
        { value: "MA", text: "Massachusetts"},
        { value: "MI", text: "Michigan"},
        { value: "MN", text: "Minnesota"},
        { value: "MS", text: "Mississippi"},
        { value: "MO", text: "Missouri"},
        { value: "MT", text: "Montana"},
        { value: "NE", text: "Nebraska"},
        { value: "NV", text: "Nevada"},
        { value: "NH", text: "New Hampshire"},
        { value: "NJ", text: "New Jersey"},
        { value: "NM", text: "New Mexico"},
        { value: "NY", text: "New York"},
        { value: "NC", text: "North Carolina"},
        { value: "ND", text: "North Dakota"},
        { value: "MP", text: "Northern Mariana Islands"},
        { value: "OH", text: "Ohio"},
        { value: "OK", text: "Oklahoma"},
        { value: "OR", text: "Oregon"},
        { value: "PW", text: "Palau"},
        { value: "PA", text: "Pennsylvania"},
        { value: "PR", text: "Puerto Rico"},
        { value: "RI", text: "Rhode Island"},
        { value: "SC", text: "South Carolina"},
        { value: "SD", text: "South Dakota"},
        { value: "TN", text: "Tennessee"},
        { value: "TX", text: "Texas"},
        { value: "UT", text: "Utah"},
        { value: "VT", text: "Vermont"},
        { value: "VI", text: "Virgin Islands"},
        { value: "VA", text: "Virginia"},
        { value: "WA", text: "Washington"},
        { value: "WV", text: "West Virginia"},
        { value: "WI", text: "Wisconsin"},
        { value: "WY", text: "Wyoming"}
    ],

    statesHash: {
        "AL": "Alabama",
        "AK": "Alaska",
        "AS": "American Samoa",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "DC": "District Of Columbia",
        "FM": "Federated States Of Micronesia",
        "FL": "Florida",
        "GA": "Georgia",
        "GU": "Guam",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MH": "Marshall Islands",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "MP": "Northern Mariana Islands",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PW": "Palau",
        "PA": "Pennsylvania",
        "PR": "Puerto Rico",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VI": "Virgin Islands",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming"
    }
});
