import Ember from 'ember';

export default Ember.Mixin.create({
    allStates: [
       "Alabama",
       "Alaska",
       "American Samoa",
       "Arizona",
       "Arkansas",
       "California",
       "Colorado",
       "Connecticut",
       "Delaware",
       "District Of Columbia",
       "Federated States Of Micronesia",
       "Florida",
       "Georgia",
       "Guam",
       "Hawaii",
       "Idaho",
       "Illinois",
       "Indiana",
       "Iowa",
       "Kansas",
       "Kentucky",
       "Louisiana",
       "Maine",
       "Marshall Islands",
       "Maryland",
       "Massachusetts",
       "Michigan",
       "Minnesota",
       "Mississippi",
       "Missouri",
       "Montana",
       "Nebraska",
       "Nevada",
       "New Hampshire",
       "New Jersey",
       "New Mexico",
       "New York",
       "North Carolina",
       "North Dakota",
       "Northern Mariana Islands",
       "Ohio",
       "Oklahoma",
       "Oregon",
       "Palau",
       "Pennsylvania",
       "Puerto Rico",
       "Rhode Island",
       "South Carolina",
       "South Dakota",
       "Tennessee",
       "Texas",
       "Utah",
       "Vermont",
       "Virgin Islands",
       "Virginia",
       "Washington",
       "West Virginia",
       "Wisconsin",
       "Wyoming"
    ],

    statesHash: {
        "AL": "Alabama",
        "AK": "Alaska",
        "AS": "American Samoa",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "DC": "District Of Columbia",
        "FM": "Federated States Of Micronesia",
        "FL": "Florida",
        "GA": "Georgia",
        "GU": "Guam",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MH": "Marshall Islands",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "MP": "Northern Mariana Islands",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PW": "Palau",
        "PA": "Pennsylvania",
        "PR": "Puerto Rico",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VI": "Virgin Islands",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming"
    }
});
