import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
    _saveTransition: function (transition) {
        var self = this;
        if (transition.targetName !== 'login') {
            self.controller.set('previousTransition', transition);
            self.controller.set('previousURL', self.get('router.url'));
        }
    },

    actions: {
        error: function(error) {
            var self = this,
                name,
                message;

            if (error) {
                // first error type is jquery's jqXHR object error (async ajax call returns error, typically menas something wrong on server side, not front end app
                if (error.promise) {
                    if (error.state() === "rejected") {
                        if (error.status === 0 && error.statusText === "error") {
                            name = "ERR_CONNECTION_REFUSED: ";
                            message = "Cannot reach the back end server.";
                        } else if (error.status === 200 && error.statusText === "OK") {
                            name = "Server Error: ";
                            message = "Server didn't return right data - is database running?";
                        } else {
                            name = "Server Error: ";
                            message = "HTTP status " + error.status + " " + error.statusText + " " + error.responseText;
                        }
                    }
                } else if (typeof error === 'string') {
                    message = error;
                    name = "Back end generated error";
                }else {
                    // internal ember error
                    // Possible error #1 data error generated by user e.g. user input different passwords to sign up
                    message = error.message;
                    name = error.name;
                }

                Ember.run(function(){
                    self.controller._toggleAlert(true, name, message, 'alert-danger');
                });
                return false;
            }
            return true;
        },

        showAlertBar: function(data) {
            var self = this;

            self.controller._toggleAlert(true, data.title, data.message, data.type);
        },

        willTransition: function (transition) {
            var self = this;

            Ember.run(function(){
                self.controller._toggleAlert(false);
            });

            self._saveTransition(transition);
        }
    }
});
