import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
    _saveTransition: function _saveTransition(transition) {
        var self = this;
        if (transition.targetName !== 'login') {
            self.controller.set('previousTransition', transition);
            self.controller.set('previousURL', self.get('router.url'));
        }
    },

    actions: {
        error: function(error) {
            var self = this,
                name,
                message;

            if (error) {
                // first error type is jquery's jqXHR object error (async ajax call returns error, typically menas something wrong on server side, not front end app
                if (error.promise) {
                    if (error.state() === "rejected") {
                        if (error.status === 0 && error.statusText === "error") {
                            name = "ERR_CONNECTION_REFUSED: ";
                            message = "Cannot reach the back end server.";
                        } else if (error.status === 200 && error.statusText === "OK") {
                            name = "Server Error: ";
                            message = "Server didn't return right data - is database running?";
                        } else {
                            name = "Server Error: ";
                            message = "HTTP status " + error.status + " " + error.statusText + " " + error.responseText;
                        }
                    }
                } else if (typeof error === 'string') {
                    message = error;
                    name = "Back end generated error";
                } else {
                    // internal ember error object { name: name, message: message }
                    // Possible error #1 data error generated by user e.g. user input different passwords to sign up
                    message = error.message;
                    name = error.name;
                }

                Ember.run(function(){
                    self.controller._toggleAlert(true, name, message, 'alert-danger');
                });
                return false;
            }
            return true;
        },

        showAlertBar: function(data) {
            var self = this;

            self.controller._toggleAlert(true, data.title, data.message, data.type);
        },

        showNewsletterSignUpBar: function() {
            var self = this;

            self.controller._toggleNewsletterSignUpAlert(true);
        },

        signUpNewsletter: function(email) {
            debugger;
            var self = this,
                session = self.get('session'),
                model = self.store.createRecord('member', {
                    email: email,
                    privilege: 0, //anonymous user
                    city: session.get('baseCity'),
                    state: session.get('baseState'),
                    zipCode: session.get('zipCode'),
                    isUser: false,
                    isDestroyed: false,
                    createdDate: new Date()}
                );

            model.save();

            self.controller._toggleNewsletterSignUpAlert(false);
            self.controller._toggleAlert(true, "Success", "Thank you for subscribing.  Please check your email inbox to confirm.", 'alert-info');
        },

        willTransition: function (transition) {
            var self = this;

            Ember.run(function(){
                self.controller._toggleAlert(false);
            });

            self._saveTransition(transition);
        },

        invalidateSession: function() {
            this.get('session').invalidate();
        }
        //sessionRequiresAuthentication: function() {
        //    debugger;
        //},
        //
        //authenticateSession: function() {
        //    debugger;
        //},

        //sessionAuthenticationSucceeded: function() {
        //    debugger;
        //},

        //sessionAuthenticationFailed: function() {
        //    debugger;
        //},
        //
        //sessionInvalidationFailed: function() {
        //    debugger;
        //},
        //
        //sessionDataUpdated: function() {
        //    debugger;
        //}
    }
});
